# Generated by Django 3.0.8 on 2020-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('mobile_num', models.BigIntegerField()),
                ('student_photo', models.ImageField(blank=True, upload_to='images/')),
                ('student_aadhar_photo', models.ImageField(blank=True, upload_to='images/')),
                ('email', models.EmailField(max_length=200)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('ipAddress', models.GenericIPAddressField()),
            ],
        ),
    ]
